package CatalystX::jQuery::Tutorial::Model::PizzaStore;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'PizzaStore::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:pizzashop',
        user => 'steve',
        password => 'ss',
    }
);

=head1 NAME

CatalystX::jQuery::Tutorial::Model::PizzaStore - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<CatalystX::jQuery::Tutorial>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<PizzaStore::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.24

=head1 AUTHOR

Steve Schafer

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
